### ISSUE TITLE
Indeck crashed when trying to load a skybox

### ISSUE THREAD

**Issue by weex** [jmiskovic/indeck#1]
Indeck crashed while I was trying to get a skybox working in the sandbox folder. This was the error displayed then.

![org lovr app-20211231-171722](https://user-images.githubusercontent.com/38776/147842174-dbd687f4-6c3e-442b-9c52-a0b769e20c2a.jpg)

I was able to get the skybox working by loading my main.lua directly, playing with texture file formats for a while. I suspect it had something to do with the jpeg and pngs I was trying to load.

**Comment by jmiskovic** [comment]
Hm that error makes little sense.

What should have happened:

1. The user code throws an error, so `lovr.errhand()` is called with error message
2. The error handler stores the message and restarts LOVR framework
3. Recovery module catches the restart, fetches error message
4. Two panes are shown, one with the error message and call stack at the moment of error, another with the code editor with opened file/line that caused the error
5. User can fix the error in code and press Ctrl+Shift+R to re-start the environment and execute the user code

The error you reported is complaining about missing `editors.lua` file which is actually included in the APK bundle and should always be available.

---

Note that I'm currently focusing on [lite-lovr](https://github.com/jmiskovic/lite-lovr/), which should be superior in every way compared to indeck. Still, even with all the limitations the indeck is still a cozy little dev environment and I'd like to make one final release with all the improvements accumulated since the first release.

Maybe you could re-test once the second release is done?

**Comment by weex** [comment]
I'll have to try the APK and lite-lovr. I was running this repo directly with the Lovr APK after resolving the symlinks through simple copies.

I really like having an editor available to work on the environment while in it.

**Comment by weex** [comment]
Closing this since I can't reproduce it.
