### ISSUE TITLE
Script crashed with APK version that worked from source

### ISSUE THREAD

**Issue by weex** [jmiskovic/indeck#2]
I've been piecing together some stuff in https://github.com/weex/magicdeck which as of [9ff5424](https://github.com/weex/magicdeck/tree/9ff54246f36f80baf80c7eefbcc26ebdef7aefa6) runs fine in the source version of indeck. Loaded the APK on the Quest and pushed this same code with `adb push --sync . /sdcard/Android/data/org.indeck.app/files/sandbox/` but got the following stack trace.

I checked and the png was shown there in Android File Transfer.
![org indeck app-20220102-215604](https://user-images.githubusercontent.com/38776/147903161-03906ef9-5d36-42ab-bd59-60b28a946429.jpg)

**Comment by weex** [comment]
Turns out this was because I was loading the texture with the wrong relative file path.

**Comment by jmiskovic** [comment]
Yeah, this is something I'm still not sure how to solve. When loading the user project (for example, the "sandbox"), the runtime adds the directory to the require path with `lovr.filesystem.setRequirePath()`. This makes all the lua files reachable by `require()` function, but textures and other data needs to use relative path (`sandbox/texture.png`).

One option would be to *mount* the user directory into root so that relative paths stay the same if project is run independently or inside the indeck. The downside is there could be file name collisions between indeck sources and user project files. In fact the conflict is guaranteed to happen because both indeck and user proj need to have `main.lua`. I've found these conflicts to be very confusing and I've wasted too much time editing a source file that wasn't even loaded because of shadowing and precedence of another source file of the same name.

So far I've dealt with this by trying to access file in both ways, first trying to open "texture.png" and if that fails try "sandbox/texture.png". While not very elegant, it's the simplest solution to make project functional both independently and within indeck. 

The same issue is affecting lite-lovr project, so far I have no good way solve it.

**Comment by weex** [comment]
For the mount option, would it help to hash the files? I'm thinking you could reference files by their hash internally so no filename collisions are possible then turn that back into a filename just for the stack trace.

Either way I think this is an interesting problem that could be its own issue.
